export ANANSI_OFF=0
export ANANSI_ON=1

export MOUSEION_OFF=0
export MOUSEION_ON=1

export ANANSI_DATA_STORAGE_CPU=1
export ANANSI_DATA_STORAGE_GPU=2

export ANANSI_LOW_COMPUTE_PRECISION=1
export ANANSI_MEDIUM_COMPUTE_PRECISION=2
export ANANSI_HIGH_COMPUTE_PRECISION=3

