# This workflow publishes Anansi's documentation

name: Publish Anansi's Documentation

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the
    # "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
# ----------------------------------------------------
# This section defines custom variables. 
# 
# Variable name         Definition
# ----------------------------------------------------
# anansi_python_env     Stores the path to the 
#                       directory that contains the Python 
#                       virtual environment.
#
# NCP_TOP_LEVEL         The top-level of the package.
#
# PIP_CACHE_DIR         pip's cache directory
# ----------------------------------------------------

env: 
    python_venv_dir: $GITHUB_WORKSPACE/anansi_python_env
    python_version: '3.9'
    ANANSI_TOP_LEVEL : $GITHUB_WORKSPACE

    # Change pip's cache directory to be inside the project directory since we
    # can only cache local items.
    PIP_CACHE_DIR: $GITHUB_WORKSPACE/.cache/pip

jobs:
    checkout_repository:
        # The runner that the job will run on.
        runs-on : [Catalan]
        steps:

        - name: Checkout Anansi 
          uses: actions/checkout@v3
          with: 
              submodules: recursive
        - name: Fetching gh-pages remote branch
          run: |
                git fetch origin gh-pages
                git branch --all
                git branch -vv

    update_gh_pages_branch:
        runs-on : [Catalan]
        needs: [checkout_repository]
        steps:
        - name: Check out gh-pages branch
          run: |
               export ANANSI_TOP_LEVEL=${{env.ANANSI_TOP_LEVEL}}
               git checkout gh-pages 
               git merge main
               ls -l ${ANANSI_TOP_LEVEL}/doxygen_documentation/html

    build_documentation:
        runs-on : [Catalan]
        needs: [update_gh_pages_branch]
        steps:
        - name: Building Anansi's documentation.
          run: |
               export ANANSI_TOP_LEVEL=${{env.ANANSI_TOP_LEVEL}}
               export ANANSI_DOXYGEN_CONFIGURATION="${ANANSI_TOP_LEVEL}/etc/anansi_doxgen.rc"
               export ANANSI_BIN_DIRECTORY="${ANANSI_TOP_LEVEL}/bin"
               export PATH="${ANANSI_BIN_DIRECTORY}:${PATH}"
               export PYTHONPATH="${ANANSI_TOP_LEVEL}/bin/lib_python:${PYTHONPATH}"
               git rm -r docs && git commit -a -m "Removed docs directory."
               build_doxygen_documentation.py --publish-mode github-pages
               git add docs && git commit -a -m "Readded docs directory."
               ls -l ${ANANSI_TOP_LEVEL}/docs/.gitkeep
               ls -l ${ANANSI_TOP_LEVEL}/docs
               git status

     push_gh_pages_branch_upstream:
#         runs-on : [Catalan]
#         needs: [merge_documentation_into_gh_pages_branch]
#         steps:
#         - run: echo "Push gh-pages branch upstream."
