# This workflow publishes Anansi's documentation

name: Publish Anansi's Documentation

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the
    # "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
# ----------------------------------------------------
# This section defines custom variables. 
# 
# Variable name         Definition
# ----------------------------------------------------
# anansi_python_env     Stores the path to the 
#                       directory that contains the Python 
#                       virtual environment.
#
# NCP_TOP_LEVEL         The top-level of the package.
#
# PIP_CACHE_DIR         pip's cache directory
# ----------------------------------------------------

env: 
    python_venv_dir: $GITHUB_WORKSPACE/anansi_python_env
    python_version: '3.9'

    # Change pip's cache directory to be inside the project directory since we
    # can only cache local items.
    PIP_CACHE_DIR: $GITHUB_WORKSPACE/.cache/pip

jobs:
    checkout_repository:
        # The runner that the job will run on.
        runs-on : [Catalan]
        steps:
        - name: Checkout Anansi 
        - run: echo "Deploying Anansi's documentation."
          uses: actions/checkout@v3
          with: 
              submodules: recursive
        - run: git fetch origin gh-pages
        - run: git branch --all
        - run: git branch -vv

    build_documentation:
        runs-on : [Catalan]
        needs: [checkout_repository]
        steps:
          - name:  "Building Anansi's documentation."
            run: echo "Building Anansi's documentation."
         

    merge_documentation_into_gh_pages_branch:
        runs-on : [Catalan]
        needs: [build_documentation]
        steps:
        - run: echo "Merging documentation into gh-pages branch."

    push_gh_pages_branch_upstream:
        runs-on : [Catalan]
        needs: [merge_documentation_into_gh_pages_branch]
        steps:
        - run: echo "Push gh-pages branch upstream."
