# This workflow publishes Anansi's documentation

name: Publish Anansi's Documentation

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the
    # "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
# ----------------------------------------------------
# This section defines custom variables. 
# 
# Variable name         Definition
# ----------------------------------------------------
# anansi_python_env     Stores the path to the 
#                       directory that contains the Python 
#                       virtual environment.
#
# NCP_TOP_LEVEL         The top-level of the package.
#
# PIP_CACHE_DIR         pip's cache directory
# ----------------------------------------------------

env: 
    python_venv_dir: $GITHUB_WORKSPACE/anansi_python_env
    python_version: '3.9'

    # Change pip's cache directory to be inside the project directory since we
    # can only cache local items.
    PIP_CACHE_DIR: $GITHUB_WORKSPACE/.cache/pip

jobs:
    # This workflow contains a single job called "deploy_documentation"
    # which publishes documentation to github-pages.
    deploy_documentation:
        # The runner that the job will run on.
        runs-on : [Catalan]
        steps:
        - run: echo "Deploying Anansi's documentation."
        - name: Checkout Anansi 
              uses: actions/checkout@v3
              with:
                    submodules: recursive 
